name: Update README with Current Time

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 mins
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set current time
        run: |
          echo "TIME=$(TZ='Asia/Kolkata' date '+%I:%M %p, %A, %d %B %Y')" >> $GITHUB_ENV

      - name: Replace placeholder in README
        run: |
          sed -i "s|<!-- TIME_PLACEHOLDER -->|🕓 $TIME|g" README.md

      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "Update time in README"
          git push
